/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src;

import java.awt.Image;
import java.io.IOException;
import java.nio.file.Path;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author erisaac666
 */
public class Reproductor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Reproductor.class.getName());
    Reproducer reproducer = new Reproducer();

    /**
     * Creates new form Reproductor
     */
    public Reproductor() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblMusica = new javax.swing.JLabel();
        lblArtista = new javax.swing.JLabel();
        lblCancion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ls1 = new javax.swing.JList<>();
        btnReproducir = new javax.swing.JButton();
        btnDetener = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 500));

        lblMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/default.jpg"))); // NOI18N

        lblArtista.setForeground(new java.awt.Color(153, 153, 153));
        lblArtista.setText("....");

        lblCancion.setForeground(new java.awt.Color(153, 153, 153));
        lblCancion.setText("....");

        ls1.setBackground(new java.awt.Color(102, 102, 102));
        ls1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Daft Punk - Veridis Quo", "Deftones - Hole in the earth", "Enjambre - Segundo tema", "The marias - Over the Moon", "The doors - Love Street" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ls1.addListSelectionListener(this::ls1ValueChanged);
        jScrollPane1.setViewportView(ls1);

        btnReproducir.setText("Reproducir");
        btnReproducir.setEnabled(false);
        btnReproducir.addActionListener(this::btnReproducirActionPerformed);

        btnDetener.setText("Detener");
        btnDetener.setEnabled(false);
        btnDetener.addActionListener(this::btnDetenerActionPerformed);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Now Playing");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnReproducir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(btnDetener)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCancion)
                            .addComponent(lblArtista))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMusica))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lblArtista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCancion)
                        .addGap(79, 79, 79)))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReproducir)
                    .addComponent(btnDetener))
                .addGap(99, 99, 99))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Reescanear musica");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowActivated

    private void ls1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ls1ValueChanged
        // TODO add your handling code here:
        if(ls1.getSelectedValue()!=null){
            btnReproducir.setEnabled(true);
        }
    }//GEN-LAST:event_ls1ValueChanged

    private void btnReproducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproducirActionPerformed
        // TODO add your handling code here:
        btnDetener.setEnabled(true);
        if(ls1.getSelectedValue().equals("Daft Punk - Veridis Quo")){
            reproducer.detener();
            lblMusica.setIcon(ajustarImagen("/assets/img/homework.jpeg",lblMusica));
            lblArtista.setText("Daft Punk");
            lblCancion.setText("Veridis Quo");
            reproducer.run("/assets/wav/Daft-Punk-Veridis-Quo.wav");
        }
        if(ls1.getSelectedValue().equals("Deftones - Hole in the earth")){
            reproducer.detener();
            lblMusica.setIcon(ajustarImagen("/assets/img/deftones.jpeg",lblMusica));
            lblArtista.setText("Deftones");
            lblCancion.setText("Hole in the Earth");
            reproducer.run("/assets/wav/Deftones-Hole-in-the-Earth.wav");
            
        }
        if(ls1.getSelectedValue().equals("Enjambre - Segundo tema")){
            reproducer.detener();
            lblMusica.setIcon(ajustarImagen("/assets/img/enjambre.jpg",lblMusica));
            lblArtista.setText("Enjambre");
            lblCancion.setText("Segundo Tema");
            reproducer.run("/assets/wav/Enjambre-Segundo-Tema.wav");
            
        }
        if(ls1.getSelectedValue().equals("The marias - Over the Moon")){
            reproducer.detener();
            lblMusica.setIcon(ajustarImagen("/assets/img/superclean.jpg",lblMusica));
            lblArtista.setText("The Marias");
            lblCancion.setText("Over the Moon");
            reproducer.run("/assets/wav/Over-the-Moon.wav");
            
            
        }
        if(ls1.getSelectedValue().equals("The doors - Love Street")){
            reproducer.detener();
            lblMusica.setIcon(ajustarImagen("/assets/img/waiting_sun.jpg",lblMusica));
            lblArtista.setText("The Doors");
            lblCancion.setText("Love Street");
            reproducer.run("/assets/wav/The-Doors-Love-Street.wav");
            
            
            
        }
        
        
    }//GEN-LAST:event_btnReproducirActionPerformed

    private void btnDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetenerActionPerformed
        // TODO add your handling code here:
        reproducer.detener();
    }//GEN-LAST:event_btnDetenerActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Path directorio = Path.of("src","assets","wav");
        try{
        List<Path> canciones = AnalizadorCanciones.buscarCanciones(directorio);
            for(Path e: canciones){
                System.out.println(e.toString());
            }
        }catch(IOException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed
private ImageIcon ajustarImagen(String ruta, javax.swing.JLabel label) {

    ImageIcon iconoOriginal = new ImageIcon(getClass().getResource(ruta));
    Image imagen = iconoOriginal.getImage();

    Image imagenEscalada = imagen.getScaledInstance(
            label.getWidth(),
            label.getHeight(),
            Image.SCALE_SMOOTH
    );

    return new ImageIcon(imagenEscalada);
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Reproductor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetener;
    private javax.swing.JButton btnReproducir;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblArtista;
    private javax.swing.JLabel lblCancion;
    private javax.swing.JLabel lblMusica;
    private javax.swing.JList<String> ls1;
    // End of variables declaration//GEN-END:variables
}
